### PR TITLE
Add flowtide.net as a third party integration

### PR DESCRIPTION
**Pull request by Ulimo**
Flowtide.NET is a streaming engine to sync data between different systems or databases.
It can denormalize permissions by converting the schema into a relational query.
It can also be used to ingest data into SpiceDB by reading data from different data sources and joining them together.

### CODE REVIEW

**Comment by josephschorr** [comment]
@Ulimo can you link to the SpiceDB-specific documentation or reference (if any)?

**Comment by Ulimo** [comment]
Here you go https://koralium.github.io/flowtide/docs/connectors/spicedb should I add it to the PR?

**Comment by Ulimo** [comment]
@josephschorr I changed the link to go directly to the connector

**Review by josephschorr — APPROVED** [review]
LGTM

**Pull request merged**
